import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import {
  Search, HelpCircle, ChevronDown, ChevronUp, ShieldCheck, Zap,
  CreditCard, Coins, MessageSquare, ArrowRight, Sparkles, CheckCircle2,
  Clock, Headphones
} from 'lucide-react'

const FAQ_CATEGORIES = [
  { id: 'all', label: 'All Topics', icon: <Sparkles size={16} /> },
  { id: 'settlement', label: 'Direct Settlement', icon: <Zap size={16} /> },
  { id: 'payment', label: 'Payment Verification', icon: <CreditCard size={16} /> },
  { id: 'security', label: 'Security & Privacy', icon: <ShieldCheck size={16} /> },
  { id: 'coins', label: 'Supported Altcoins', icon: <Coins size={16} /> },
]

const FAQS = [
  {
    category: 'settlement',
    q: 'How does Kryptella direct settlement work?',
    a: 'Kryptella operates on a 100% direct settlement model. You select your cryptocurrency and naira amount, provide your external wallet address, and make a standard bank payment. Once verified, our automated liquidity engine broadcasts the crypto directly to your personal address on-chain. You never have to wait for wallet funding or manage an internal custodial balance.',
  },
  {
    category: 'settlement',
    q: 'Do I need to fund an internal Kryptella account first?',
    a: 'No! Unlike traditional exchanges that force you to deposit money into an account before trading, Kryptella requires ZERO wallet funding. Every transaction is a direct purchase settled straight to your private wallet address.',
  },
  {
    category: 'settlement',
    q: 'How long does blockchain delivery take?',
    a: 'Under normal network conditions, payments are verified in under 2 minutes, and crypto is dispatched instantly. Blockchain confirmation times depend on the specific chain (e.g., Solana takes ~30 seconds, BEP-20/Polygon takes ~1 minute, Bitcoin takes 1-2 block confirmations).',
  },
  {
    category: 'settlement',
    q: 'Can I send crypto directly to hardware wallets like Ledger or Trezor?',
    a: 'Yes, absolutely! Because Kryptella settles directly on the blockchain, you can input your hardware wallet (Ledger, Trezor), mobile wallet (Trust Wallet, Phantom, Metamask), or any valid public address on the supported network.',
  },
  {
    category: 'payment',
    q: 'How do I pay for my crypto order?',
    a: 'When you create a buy order, Kryptella generates a dedicated order checkout with our designated corporate bank details. You simply open your regular banking mobile app or internet banking and perform a transfer for the exact order amount.',
  },
  {
    category: 'payment',
    q: 'What payment receipts and proofs are accepted?',
    a: 'We accept standard PDF or image screenshots generated by your commercial bank or fintech app showing the transaction date, amount, sender name, and bank transaction reference. Upload this receipt in your order panel for automated verification.',
  },
  {
    category: 'payment',
    q: 'What happens if my bank transfer is delayed?',
    a: 'Interbank delays can happen occasionally. If your transfer takes longer to reflect in our accounts, your order status will automatically update as soon as the funds clear. You can also reach out directly to our 24/7 Concierge with your transaction session ID for priority tracing.',
  },
  {
    category: 'payment',
    q: 'Are there any hidden spreads or surprise fees?',
    a: 'None. The rate and naira total displayed on checkout are fully inclusive of liquidity routing and standard blockchain network dispatch costs. What you see is what you pay.',
  },
  {
    category: 'security',
    q: 'Do you hold or store my crypto private keys?',
    a: 'Never. Kryptella is strictly non-custodial. We never generate, store, or have access to your private keys or seed phrases. You maintain complete, sovereign ownership of your crypto at all times.',
  },
  {
    category: 'security',
    q: 'How does Kryptella protect my transaction data?',
    a: 'All communications and payment receipts are encrypted end-to-end with enterprise-grade 256-bit SSL/TLS protocols. Proof of payment uploads are isolated and strictly handled in compliance with stringent data confidentiality standards.',
  },
  {
    category: 'coins',
    q: 'Which cryptocurrencies and networks are supported?',
    a: 'Kryptella supports over 20 top cryptocurrencies including Bitcoin (BTC native), Ethereum (ERC-20, Arbitrum, Optimism), Tether (USDT on TRC-20, BEP-20, ERC-20), Solana (SOL native), Binance Coin (BNB), Ripple (XRP), Cardano (ADA), Dogecoin, and more.',
  },
  {
    category: 'coins',
    q: 'What should I do if I entered the wrong wallet network?',
    a: 'Because blockchain transfers are irreversible once dispatched, it is crucial to ensure that your destination address matches the network selected (e.g. TRC-20 vs ERC-20). If you notice an error before payment verification, you can cancel and recreate the order or alert our 24/7 Concierge immediately.',
  },
]

export default function HelpCenter() {
  const [search, setSearch] = useState('')
  const [selectedCategory, setSelectedCategory] = useState('all')
  const [openFaq, setOpenFaq] = useState(0)

  const filteredFaqs = FAQS.filter((faq) => {
    const matchesCat = selectedCategory === 'all' || faq.category === selectedCategory
    const matchesQuery =
      faq.q.toLowerCase().includes(search.toLowerCase()) ||
      faq.a.toLowerCase().includes(search.toLowerCase())
    return matchesCat && matchesQuery
  })

  return (
    <div style={{ background: 'var(--bg-primary)', color: 'var(--text-primary)', minHeight: '100vh', paddingTop: 88, paddingBottom: 80 }}>
      {/* Header Hero */}
      <section
        style={{
          padding: '60px 0 40px',
          background: 'radial-gradient(ellipse 80% 60% at 50% 10%, rgba(59, 130, 246, 0.22) 0%, transparent 70%)',
          position: 'relative',
        }}
      >
        <div className="container" style={{ textAlign: 'center', maxWidth: 760 }}>
          <div
            className="luxury-glow-badge"
            style={{ marginBottom: 20 }}
          >
            <HelpCircle size={14} color="#60A5FA" />
            <span>Kryptella Knowledge Base & Concierge</span>
          </div>

          <h1
            style={{
              fontSize: 'clamp(32px, 5vw, 52px)',
              fontWeight: 900,
              letterSpacing: '-1.5px',
              color: '#FFFFFF',
              marginBottom: 18,
            }}
          >
            How Can We Assist You?
          </h1>
          <p style={{ fontSize: 17, color: '#94A3B8', lineHeight: 1.7, marginBottom: 36 }}>
            Explore guides on direct blockchain settlement, payment verification, security frameworks, and supported altcoin networks.
          </p>

          {/* Search Box */}
          <div
            className="card-glass"
            style={{
              display: 'flex',
              alignItems: 'center',
              padding: '8px 16px',
              maxWidth: 620,
              margin: '0 auto',
              boxShadow: '0 12px 36px rgba(0, 0, 0, 0.5), 0 0 20px rgba(59, 130, 246, 0.2)',
            }}
          >
            <Search size={20} color="#60A5FA" style={{ marginRight: 12, flexShrink: 0 }} />
            <input
              type="text"
              placeholder="Search direct settlements, proof of payment, wallet delivery..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              style={{
                width: '100%',
                background: 'transparent',
                border: 'none',
                color: '#FFFFFF',
                fontSize: 16,
                outline: 'none',
              }}
            />
            {search && (
              <button
                onClick={() => setSearch('')}
                style={{
                  background: 'none',
                  border: 'none',
                  color: '#94A3B8',
                  fontSize: 13,
                  cursor: 'pointer',
                  fontWeight: 600,
                }}
              >
                Clear
              </button>
            )}
          </div>
        </div>
      </section>

      {/* Category Pills */}
      <section style={{ padding: '24px 0 36px' }}>
        <div className="container">
          <div style={{ display: 'flex', gap: 10, justifyContent: 'center', flexWrap: 'wrap' }}>
            {FAQ_CATEGORIES.map((cat) => (
              <button
                key={cat.id}
                onClick={() => setSelectedCategory(cat.id)}
                className={selectedCategory === cat.id ? 'btn btn-glass-primary' : 'btn btn-glass-secondary'}
                style={{
                  padding: '9px 18px',
                  borderRadius: 9999,
                  fontSize: 14,
                  fontWeight: 600,
                  cursor: 'pointer',
                }}
              >
                {cat.icon}
                <span>{cat.label}</span>
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* FAQs Accordion Grid */}
      <section style={{ padding: '20px 0 60px' }}>
        <div className="container" style={{ maxWidth: 880 }}>
          {filteredFaqs.length === 0 ? (
            <div className="card-glass" style={{ textAlign: 'center', padding: '60px 24px' }}>
              <HelpCircle size={44} color="#60A5FA" style={{ margin: '0 auto 16px' }} />
              <h3 style={{ fontSize: 20, fontWeight: 700, color: '#fff', marginBottom: 8 }}>No matching topics found</h3>
              <p style={{ color: '#94A3B8', marginBottom: 24 }}>
                We couldn't find an answer for "{search}". Speak directly with our 24/7 concierge desk.
              </p>
              <Link to="/contact" className="btn btn-glass-primary">
                <span>Contact 24/7 Concierge</span>
                <ArrowRight size={16} />
              </Link>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              {filteredFaqs.map((faq, index) => {
                const isOpen = openFaq === index
                return (
                  <div
                    key={index}
                    className="card-glass"
                    style={{
                      borderRadius: 16,
                      border: isOpen ? '1px solid rgba(96, 165, 250, 0.45)' : '1px solid rgba(56, 189, 248, 0.16)',
                      background: isOpen ? 'rgba(16, 29, 64, 0.75)' : 'var(--glass-bg-card)',
                      transition: 'all 0.25s ease',
                    }}
                  >
                    <button
                      onClick={() => setOpenFaq(isOpen ? null : index)}
                      style={{
                        width: '100%',
                        padding: '22px 26px',
                        background: 'none',
                        border: 'none',
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        textAlign: 'left',
                        cursor: 'pointer',
                        color: '#FFFFFF',
                        gap: 16,
                      }}
                    >
                      <span style={{ fontSize: 17, fontWeight: 700, letterSpacing: '-0.3px', lineHeight: 1.4 }}>
                        {faq.q}
                      </span>
                      <div
                        style={{
                          width: 32,
                          height: 32,
                          borderRadius: '50%',
                          background: isOpen ? 'rgba(59, 130, 246, 0.2)' : 'rgba(255, 255, 255, 0.05)',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          color: isOpen ? '#60A5FA' : '#94A3B8',
                          flexShrink: 0,
                          transition: 'all 0.2s',
                        }}
                      >
                        {isOpen ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                      </div>
                    </button>
                    {isOpen && (
                      <div
                        style={{
                          padding: '0 26px 22px',
                          color: '#CBD5E1',
                          fontSize: 15,
                          lineHeight: 1.75,
                          borderTop: '1px solid rgba(255, 255, 255, 0.05)',
                          paddingTop: 16,
                        }}
                      >
                        {faq.a}
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          )}
        </div>
      </section>

      {/* Direct Concierge Assistance Banner */}
      <section style={{ padding: '20px 0' }}>
        <div className="container" style={{ maxWidth: 880 }}>
          <div
            className="card-glass"
            style={{
              padding: '36px 32px',
              borderRadius: 24,
              background: 'linear-gradient(135deg, rgba(14, 25, 58, 0.85) 0%, rgba(8, 14, 32, 0.95) 100%)',
              border: '1px solid rgba(96, 165, 250, 0.3)',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              flexWrap: 'wrap',
              gap: 24,
              boxShadow: '0 20px 50px rgba(0, 0, 0, 0.6), 0 0 30px rgba(59, 130, 246, 0.15)',
            }}
          >
            <div style={{ maxWidth: 520 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: '#F59E0B', fontSize: 13, fontWeight: 700, marginBottom: 8 }}>
                <Headphones size={16} /> 24/7 DEDICATED CONCIERGE
              </div>
              <h3 style={{ fontSize: 24, fontWeight: 900, color: '#FFFFFF', marginBottom: 8 }}>
                Require Dedicated Transaction Support?
              </h3>
              <p style={{ color: '#94A3B8', fontSize: 14, lineHeight: 1.65, margin: 0 }}>
                Our senior crypto liquidity desk is standing by around the clock. Average response under 5 minutes on WhatsApp, Telegram, or email.
              </p>
            </div>
            <Link to="/contact" className="btn btn-glass-primary btn-lg">
              <span>Contact Concierge Desk</span>
              <ArrowRight size={18} />
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}
